/*
**    Chromis POS  - The New Face of Open Source POS
**    Copyright (c)2015-2016
**    http://www.chromis.co.uk
**
**    This file is part of Chromis POS Version V0.60.2 beta
**
**    Chromis POS is free software: you can redistribute it and/or modify
**    it under the terms of the GNU General Public License as published by
**    the Free Software Foundation, either version 3 of the License, or
**    (at your option) any later version.
**
**    Chromis POS is distributed in the hope that it will be useful,
**    but WITHOUT ANY WARRANTY; without even the implied warranty of
**    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**    GNU General Public License for more details.
**
**    You should have received a copy of the GNU General Public License
**    along with Chromis POS.  If not, see <http://www.gnu.org/licenses/>
**
**
 */
package uk.chromis.pos.ticket;

import java.util.List;
import uk.chromis.basic.BasicException;
import uk.chromis.data.gui.ComboBoxValModel;
import uk.chromis.data.loader.QBFCompareEnum;
import uk.chromis.data.loader.SentenceList;
import uk.chromis.data.user.EditorCreator;
import uk.chromis.editor.JEditorKeys;
import uk.chromis.editor.JEditorString;
import uk.chromis.pos.forms.AppLocal;
import uk.chromis.pos.forms.DataLogicSales;

/**
 *
 *
 */
public class ProductFilterSalesSearch extends javax.swing.JPanel implements EditorCreator {

    private final SentenceList m_sentcat;
    private ComboBoxValModel m_CategoryModel;
    private String siteGuid;

    /**
     * Creates new form ProductFilterSales
     *
     * @param dlSales
     * @param jKeys
     */
    public ProductFilterSalesSearch(DataLogicSales dlSales, JEditorKeys jKeys, String siteGuid) {
        initComponents();

        this.siteGuid = siteGuid;

        m_jtxtBarCode.addEditorKeys(jKeys);
        m_jtxtName.addEditorKeys(jKeys);

        m_sentcat = dlSales.getCategoriesList(siteGuid);
        m_CategoryModel = new ComboBoxValModel();

    }

    /**
     *
     */
    public void activate() {

        m_jtxtBarCode.reset();
        m_jtxtBarCode.setEditModeEnum(JEditorString.MODE_123);
        m_jtxtBarCode.activate();
        m_jtxtName.reset();
        jInStock.setSelected(false);

        try {
            List catlist = m_sentcat.list();
            catlist.add(0, null);
            m_CategoryModel = new ComboBoxValModel(catlist);
            m_jCategory.setModel(m_CategoryModel);
        } catch (BasicException eD) {

        }
    }

    @Override
    public Object createValue() throws BasicException {

        Object[] afilter = new Object[8];

        if (jInStock.isSelected()) {
            afilter[2] = QBFCompareEnum.COMP_GREATER;
            afilter[3] = 0.0;
        } else {
            afilter[2] = QBFCompareEnum.COMP_NONE;
            afilter[3] = null;
        }

        if (m_jtxtBarCode.getText() == null || m_jtxtBarCode.getText().equals("")) {
            afilter[0] = QBFCompareEnum.COMP_NONE;
            afilter[1] = null;
        } else {
            afilter[0] = QBFCompareEnum.COMP_RE;
            afilter[1] = m_jtxtBarCode.getText();
            afilter[4] = QBFCompareEnum.COMP_NONE;
            afilter[5] = null;
            afilter[6] = QBFCompareEnum.COMP_NONE;
            afilter[7] = null;
            return afilter;

        }

        if (m_jtxtName.getText() == null || m_jtxtName.getText().equals("")) {
            afilter[4] = QBFCompareEnum.COMP_NONE;
            afilter[5] = null;
        } else {
            afilter[4] = QBFCompareEnum.COMP_RE;
            afilter[5] = m_jtxtName.getText();
        }

        if (m_CategoryModel.getSelectedKey() == null) {
            afilter[6] = QBFCompareEnum.COMP_NONE;
            afilter[7] = null;
        } else {
            afilter[6] = QBFCompareEnum.COMP_EQUALS;
            afilter[7] = m_CategoryModel.getSelectedKey();
        }

        return afilter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jtxtBarCode = new uk.chromis.editor.JEditorString();
        m_jtxtName = new uk.chromis.editor.JEditorString();
        m_jCategory = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jInStock = new javax.swing.JCheckBox();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(370, 200));
        setLayout(null);

        m_jtxtBarCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        add(m_jtxtBarCode);
        m_jtxtBarCode.setBounds(130, 10, 290, 25);

        m_jtxtName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        add(m_jtxtName);
        m_jtxtName.setBounds(130, 40, 290, 25);

        m_jCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(m_jCategory);
        m_jCategory.setBounds(130, 70, 260, 25);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText(AppLocal.getIntString("label.prodbarcode")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(20, 10, 110, 25);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText(AppLocal.getIntString("label.prodname")); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(20, 40, 110, 25);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText(AppLocal.getIntString("label.prodcategory")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 70, 110, 25);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText(AppLocal.getIntString("label.showinstockonly")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(20, 100, 110, 25);
        add(jInStock);
        jInStock.setBounds(130, 100, 30, 21);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jInStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox m_jCategory;
    private uk.chromis.editor.JEditorString m_jtxtBarCode;
    private uk.chromis.editor.JEditorString m_jtxtName;
    // End of variables declaration//GEN-END:variables

}
