/*
**    Chromis POS  - The New Face of Open Source POS
**    Copyright (c)2015-2016
**    http://www.chromis.co.uk
**
**    This file is part of Chromis POS Version V0.60.2 beta
**
**    Chromis POS is free software: you can redistribute it and/or modify
**    it under the terms of the GNU General Public License as published by
**    the Free Software Foundation, either version 3 of the License, or
**    (at your option) any later version.
**
**    Chromis POS is distributed in the hope that it will be useful,
**    but WITHOUT ANY WARRANTY; without even the implied warranty of
**    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**    GNU General Public License for more details.
**
**    You should have received a copy of the GNU General Public License
**    along with Chromis POS.  If not, see <http://www.gnu.org/licenses/>
**
**
*/

package uk.chromis.pos.inventory;

import java.awt.Component;
import java.util.UUID;
import uk.chromis.basic.BasicException;
import uk.chromis.data.user.DirtyManager;
import uk.chromis.data.user.EditorRecord;
import uk.chromis.format.Formats;
import uk.chromis.pos.forms.AppLocal;

/**
 *
 * @author adrianromero
 */
public final class LocationsView extends javax.swing.JPanel implements EditorRecord {

    // private DirtyManager m_Dirty = new DirtyManager();    
    private String m_sID;
    private String siteGuid;

    /**
     * Creates new form LocationsEditor
     *
     * @param dirty
     */
    public LocationsView(DirtyManager dirty, String siteGuid) {
        initComponents();
        this.siteGuid = siteGuid;
        m_jName.getDocument().addDocumentListener(dirty);
        m_jAddress.getDocument().addDocumentListener(dirty);

        writeValueEOF();
    }

    /**
     *
     */
    @Override
    public void writeValueEOF() {

        m_sID = null;
        m_jSID.setText(null);
        m_jName.setText(null);
        m_jAddress.setText(null);

        m_jSID.setEnabled(false);
        m_jName.setEnabled(false);
        m_jAddress.setEnabled(false);
    }

    /**
     *
     */
    @Override
    public void writeValueInsert() {

        m_sID = UUID.randomUUID().toString();
        m_jSID.setText(null);
        m_jName.setText(null);
        m_jAddress.setText(null);

        m_jSID.setEnabled(true);
        //Disabled the form from being editable
        m_jSID.setEditable(false);
        m_jName.setEnabled(true);
        m_jAddress.setEnabled(true);
    }

    /**
     *
     * @param value
     */
    @Override
    public void writeValueDelete(Object value) {

        Object[] location = (Object[]) value;
        m_sID = Formats.STRING.formatValue(location[0]);
        m_jSID.setText(Formats.STRING.formatValue(location[0]));
        m_jName.setText(Formats.STRING.formatValue(location[1]));
        m_jAddress.setText(Formats.STRING.formatValue(location[2]));

        m_jSID.setEnabled(false);
        m_jName.setEnabled(false);
        m_jAddress.setEnabled(false);
    }

    /**
     *
     * @param value
     */
    @Override
    public void writeValueEdit(Object value) {

        Object[] location = (Object[]) value;
        m_sID = Formats.STRING.formatValue(location[0]);
        m_jSID.setText(Formats.STRING.formatValue(location[0]));
        m_jName.setText(Formats.STRING.formatValue(location[1]));
        m_jAddress.setText(Formats.STRING.formatValue(location[2]));

        m_jSID.setEnabled(true);
        //Disabled the form from being editable
        m_jSID.setEditable(false);
        m_jName.setEnabled(true);
        m_jAddress.setEnabled(true);
        siteGuid = location[3].toString();
    }

    /**
     *
     * @return @throws BasicException
     */
    @Override
    public Object createValue() throws BasicException {
        Object[] location = new Object[4];
        location[0] = m_sID;
        location[1] = m_jName.getText();
        location[2] = m_jAddress.getText();
        location[3] = siteGuid;
        return location;
    }

    /**
     *
     * @return
     */
    @Override
    public Component getComponent() {
        return this;
    }

    /**
     *
     */
    @Override
    public void refresh() {
    }

    @Override
    public void refreshGuid(String siteGuid) {
        this.siteGuid = siteGuid;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        m_jAddress = new javax.swing.JTextField();
        m_jSID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText(AppLocal.getIntString("label.locationname")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 50, 150, 25);

        m_jName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        add(m_jName);
        m_jName.setBounds(180, 50, 260, 25);

        m_jAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        add(m_jAddress);
        m_jAddress.setBounds(180, 80, 260, 25);

        m_jSID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        add(m_jSID);
        m_jSID.setBounds(180, 20, 260, 25);

        jLabel1.setText("ID");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 11, 30);

        jLabel4.setText("<html>Use the location ID to configure the location of this <br/> terminal in Menu->Resources->*hostname*/Properties");
        add(jLabel4);
        jLabel4.setBounds(20, 160, 320, 70);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText(AppLocal.getIntString("label.locationaddress")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(20, 80, 80, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField m_jAddress;
    private javax.swing.JTextField m_jName;
    private javax.swing.JTextField m_jSID;
    // End of variables declaration//GEN-END:variables



}
